---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: provisioneddashboards
  labels:
    crossplane.io/xrd: provisioneddashboards.grafana.kanopy-platform.github.io
    provider: grafana
spec:
  compositeTypeRef:
    apiVersion: grafana.kanopy-platform.github.io/v1beta1
    kind: ProvisionedDashboard
  writeConnectionSecretsToNamespace: crossplane-system
  resources:
  - name: dashboard
    base:
      apiVersion: oss.grafana.crossplane.io/v1alpha1
      kind: Dashboard
      spec:
        providerConfigRef:
          name: provisioneddashboards
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.config
      toFieldPath: spec.forProvider.configJson
      policy:
        fromFieldPath: Required
    - type: FromCompositeFieldPath
      fromFieldPath: spec.folderRef
      toFieldPath: spec.forProvider.folderRef.name
    - type: FromCompositeFieldPath
      fromFieldPath: spec.namespace
      toFieldPath: spec.providerConfigRef.name
      policy:
        fromFieldPath: Required
...
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: provisionedfolders
  labels:
    crossplane.io/xrd: provisionedfolders.grafana.kanopy-platform.github.io
    provider: grafana
spec:
  compositeTypeRef:
    apiVersion: grafana.kanopy-platform.github.io/v1beta1
    kind: ProvisionedFolder
  writeConnectionSecretsToNamespace: crossplane-system
  resources:
  - name: folder
    base:
      apiVersion: oss.grafana.crossplane.io/v1alpha1
      kind: Folder
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.deletionPolicy
      toFieldPath: spec.deletionPolicy
    - type: FromCompositeFieldPath
      fromFieldPath: spec.folderTitle
      toFieldPath: spec.forProvider.title
      policy:
        fromFieldPath: Required
    - type: FromCompositeFieldPath
      fromFieldPath: spec.namespace
      toFieldPath: spec.providerConfigRef.name
      policy:
        fromFieldPath: Required
    - type: FromCompositeFieldPath
      fromFieldPath: metadata.name
      toFieldPath: metadata.name
...
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: provisioneddatasources
  labels:
    crossplane.io/xrd: provisioneddatasources.grafana.kanopy-platform.github.io
    provider: grafana
spec:
  compositeTypeRef:
    apiVersion: grafana.kanopy-platform.github.io/v1beta1
    kind: ProvisionedDataSource
  writeConnectionSecretsToNamespace: crossplane-system
  resources:
  - name: datasource
    base:
      apiVersion: oss.grafana.crossplane.io/v1alpha1
      kind: DataSource
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.accessMode
      toFieldPath: spec.forProvider.accessMode
    - type: FromCompositeFieldPath
      fromFieldPath: spec.basicAuth
      toFieldPath: spec.forProvider.basicAuthEnabled
    - type: FromCompositeFieldPath
      fromFieldPath: spec.basicAuthUsername
      toFieldPath: spec.forProvider.basicAuthUsername
    - type: FromCompositeFieldPath
      fromFieldPath: spec.databaseName
      toFieldPath: spec.forProvider.databaseName
    - type: FromCompositeFieldPath
      fromFieldPath: spec.default
      toFieldPath: spec.forProvider.isDefault
    - type: FromCompositeFieldPath
      fromFieldPath: spec.type
      toFieldPath: spec.forProvider.type
      policy:
        fromFieldPath: Required
    - type: FromCompositeFieldPath
      fromFieldPath: spec.config
      toFieldPath: spec.forProvider.jsonDataEncoded
    - type: FromCompositeFieldPath
      fromFieldPath: spec.secureConfig
      toFieldPath: spec.forProvider.secureJsonDataEncoded
    - type: FromCompositeFieldPath
      fromFieldPath: spec.secureConfigRef
      toFieldPath: spec.forProvider.secureJsonDataEncodedSecretRef
    - type: FromCompositeFieldPath
      fromFieldPath: spec.name
      toFieldPath: spec.forProvider.name
      policy:
        fromFieldPath: Required
    - type: FromCompositeFieldPath
      fromFieldPath: spec.namespace
      toFieldPath: spec.providerConfigRef.name
      policy:
        fromFieldPath: Required
    - type: FromCompositeFieldPath
      fromFieldPath: spec.url
      toFieldPath: spec.forProvider.url
      policy:
        fromFieldPath: Required
...
