---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: provisioneddashboards
  labels:
    crossplane.io/xrd: provisioneddashboards.grafana.kanopy-platform.github.io
    provider: grafana
spec:
  compositeTypeRef:
    apiVersion: grafana.kanopy-platform.github.io/v1beta1
    kind: ProvisionedDashboard
  writeConnectionSecretsToNamespace: crossplane-system
  resources:
  - name: dashboard
    base:
      apiVersion: oss.grafana.crossplane.io/v1alpha1
      kind: Dashboard
      spec:
        providerConfigRef:
          name: provisioneddashboards
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.config
      toFieldPath: spec.forProvider.configJson
      policy:
        fromFieldPath: Required
    - type: FromCompositeFieldPath
      fromFieldPath: spec.orgID
      toFieldPath: spec.forProvider.orgId
      policy:
        fromFieldPath: Required
    - type: FromCompositeFieldPath
      fromFieldPath: spec.folderID
      toFieldPath: spec.forProvider.folder
---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: provisionedfolders
  labels:
    crossplane.io/xrd: provisionedfolders.grafana.kanopy-platform.github.io
    provider: grafana
spec:
  compositeTypeRef:
    apiVersion: grafana.kanopy-platform.github.io/v1beta1
    kind: ProvisionedFolder
  writeConnectionSecretsToNamespace: crossplane-system
  resources:
  - name: folder
    base:
      apiVersion: oss.grafana.crossplane.io/v1alpha1
      kind: Folder
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.deletionPolicy
      toFieldPath: spec.deletionPolicy
    - type: FromCompositeFieldPath
      fromFieldPath: spec.folderTitle
      toFieldPath: spec.forProvider.title
      policy:
        fromFieldPath: Required
    - type: FromCompositeFieldPath
      fromFieldPath: spec.providerConfigName
      toFieldPath: spec.providerConfigRef.name
...
