---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  creationTimestamp: null
  name: provisionedfolders.grafana.kanopy-platform.github.io
spec:
  enforcedCompositionRef:
    name: provisionedfolders
  group: grafana.kanopy-platform.github.io
  names:
    kind: ProvisionedFolder
    listKind: ProvisionedFolderList
    plural: provisionedfolders
    singular: provisionedfolder
  versions:
  - name: v1beta1
    referenceable: true
    schema:
      openAPIV3Schema:
        description: Grafana Folder resource.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              deletionpolicy:
                type: string
              foldertitle:
                type: string
              folderuid:
                type: string
              namespace:
                type: string
            required:
            - foldertitle
            - namespace
            type: object
        type: object
    served: true
