---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  creationTimestamp: null
  name: provisioneddatasources.grafana.kanopy-platform.github.io
spec:
  enforcedCompositionRef:
    name: provisioneddatasources
  group: grafana.kanopy-platform.github.io
  names:
    kind: ProvisionedDataSource
    listKind: ProvisionedDataSourceList
    plural: provisioneddatasources
    singular: provisioneddatasource
  versions:
  - name: v1beta1
    referenceable: true
    schema:
      openAPIV3Schema:
        description: infrastructure resources.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              accessMode:
                enum:
                - proxy
                - direct
                type: string
              basicAuth:
                type: boolean
              basicAuthUsername:
                type: string
              config:
                type: string
              databaseName:
                type: string
              default:
                type: boolean
              name:
                type: string
              namespace:
                type: string
              secureConfigRef:
                properties:
                  key:
                    type: string
                  name:
                    type: string
                  namespace:
                    type: string
                required:
                - key
                - name
                - namespace
                type: object
              type:
                type: string
              url:
                type: string
            required:
            - name
            - namespace
            - type
            - url
            type: object
        type: object
    served: true
